name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update 
      - run: sudo apt-get install -y gcc
      - run: sudo apt-get install -y cmake
      - run: sudo apt-get install -y cpputest
      - run: sudo mkdir /usr/CppUTest
      - run: sudo mkdir /usr/CppUTest/lib/
      - run: sudo cp -r /usr/include/CppUTest /usr/CppUTest/include
      - run: sudo cp /usr/lib/x86_64-linux-gnu/libCppUTest.a /usr/CppUTest/lib
      - run: sudo ls /usr/CppUTest/lib

